
# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
/run/numberOfThreads 10
/run/initialize
/run/printProgress 500000
#
/control/verbose 2
/run/verbose 2

# Форма 
/gps/source/type Plane
/gps/shape Square
/gps/halfx 2.5 cm   # 5 см / 2
/gps/halfy 2.5 cm   # 5 см / 2               

# Задаём частицу
/gps/particle gamma
/gps/direction 0 0 -1
/gps/ang/type beam
/gps/pos/centre 0 0 90 cm
/gps/pos/type Volume
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
               
# Спектр частицы
/gps/ene/type Arb
/gps/hist/file ./spectre.txt
/gps/hist/inter Lin
            

/score/create/boxMesh boxMesh_1
/score/mesh/boxSize 100. 100. 100. cm
/score/mesh/nBin 30 30 30
/score/quantity/energyDeposit eDep
/score/close 
/run/beamOn 100000000
/score/dumpQuantityToFile boxMesh_1 eDep "energyDeposit.csv"